### ISSUE TITLE
Scope?

### ISSUE THREAD

**Issue by matthiasbeyer** [nix-community/NUR#1]
It is not entirely clear what this repository is for.

**I** would like to use my local overlay files and push them to this repository. For example, I would create `./pkgs/applications/network/mailreaders/lumail/lumail-master.nix` for an overlay which is for building the "lumail" mail reader from the master branch of the project.

But because of the word "index" in the README, I'm not sure whether this repository should be a "collection of links to overlay repositories" or a collection of overlays.

**Comment by Mic92** [comment]
@matthiasbeyer the later one.

**Comment by Mic92** [comment]
I envisioned NUR as a kind of overlay manager/central registry.

**Comment by zimbatm** [comment]
Is the name a play on ArchLinux's AUR?

In AUR each package is a new git repo in a flat layout. Each repo is managed by a set of owners and advances independently from the rest.

**Comment by Mic92** [comment]
For users a flat layout would be easier to discover since they could call packages by name. It would also allow to move maintenance from one maintainer to the other.
For developer repositories are more convenient since they only need one repository and can also share common expressions.

Ideally we could have both. That we feed repositories into NUR and get a flat hierarchy out of it. The only question is how duplicate are resolved.

**Comment by samueldr** [comment]
Talking about duplicates, this is a hard problem to solve. Maybe it's much easier to understand for everyone to not flatten the repo, so `samueldr.something` and `Mic92.something` both can coexist, and are easy to differentiate. That is especially important so there's no surprise as to where `something` comes from for the end-user. This would also make it easier on the CLI to differentiate (e.g. on a nix-shell) where `something` comes from. `nix-shell -p something` from nixpkgs/your system;  `nix-shell -p someone.something` from someone.

**Comment by samueldr** [comment]
Since there is a lock file, acting on merge to master to update a database (e.g. json file) with the contents of an eval should be possible, like the Makefile does for nixos-homepage. From there, either a web interface or a CLI could handle searching through the data.

**Comment by zimbatm** [comment]
What about introducing two different concepts: apps and package sets.

Packages sets are for cluster of packages that work well together, like the gnome 3 or kde apps collection. Scientific package set. Or stackage LTS. Generally they are designed and tested to work together. Most of the time they also try to coordinate releases.

Apps are leafy and unique. It's unlikely that other packages would depend on them and hopefully all the dependencies are already either available upstream in nixpkgs or they are pinned to this specific release. The name should be unique enough to avoid duplicate collision. Like docker images have a `docker-` prefix convention on github we would also introduce a `nixpkg-` prefix.

Things that are used by everyone then get pushed to nixpkgs.

**Comment by samueldr** [comment]
FWIW, my opinion is to not be opinionated on the actual overlays, but to provide guidance on how to build them, *especially for future upstreaming purposes* or when packaging backports. This keeps the NUR more simple, to the expense of being harder to make an overlay depend on another (does it?).

**Comment by Mic92** [comment]
With the new readme the scope should be clear: https://github.com/nix-community/NUR
