### ISSUE TITLE
Impure attribute fails due to restricted-eval mode

### ISSUE THREAD

**Issue by mpickering** [nix-community/NUR#108]
Related to #92.

I wanted to distribute an impure attribute which would drop users into a shell environment with the latest 
ghcHEAD release. The way this is achieved is by using `builtins.fetchurl` pointed at a URL which redirects to the lastest artifact. 

However trying to add this to NUR fails as NUR seems to want to evaluate the expression before adding it 
to the repo so the call to `fetchurl` fails.

https://travis-ci.com/nix-community/NUR/jobs/170816780#L618

It seems that this kind of derivation is impossible to distribute with NUR currently.

**Comment by zimbatm** [comment]
It's possible but with a level of indirection. You could distribute a script, that invokes `nix-shell ${./.}`

**Comment by mpickering** [comment]
@zimbatm That is the solution I have gone for in the end as it gives me some more opportunities for indirection. 

I am getting some errors trying to run such a script though after installing it globally but that's another issue. 

```
error: restoring parent mount namespace: Invalid argument
```
