### ISSUE TITLE
How to use the toPythonModule function with NUR?

### ISSUE THREAD

**Issue by smaret** [nix-community/NUR#114]
I've posted this question on [discourse](https://discourse.nixos.org/t/packaging-an-application-with-python-bindings-in-nur/2018)  originally, but it did not receive much attention.

I would like to package an application (`astrochem`) that has Python bindings in NUR. In the `nixpkgs` tree, I would add the following line to `python-packages.nix`:

```nix
astrochem = toPythonModule (pkgs.astrochem.override { pythonPackages = self; });
```
 
I've tried something similar in in the `default.nix` of a `nur-packages-templates` fork:

```nix
astrochem = pkgs.pythonPackages.toPythonModule ((pkgs.callPackage ./pkgs/astrochem {pythonPackages = self; }).override { }); 
```

but then I get the following error:

```
nix-build -I . -A python27Packages.astrochem
error: undefined variable 'self' at /Users/smaret/Documents/Software/nur-packages/default.nix:18:103
```

How can I use the `toPythonModule` function in NUR?

**Comment by Mic92** [comment]
Does this work?

```
astrochem = pkgs.pythonPackages.toPythonModule (
  (pkgs.callPackage ./pkgs/astrochem { inherit (pkgs) pythonPackages; }).override { }
); 
```

**Comment by Mic92** [comment]
Make sure to use the same `pythonPackages` version as `astrochem`.

**Comment by Moredread** [comment]
@Mic92 On that note, can you get the pythonPackages used from the package attrset, i.e. via astrochem.<smth>?

**Comment by Mic92** [comment]
@Moredread I found:

nix-repl> python3.pkgs.mypy.pythonModule.pkgs

I think this one should also work if you don't plan to override any python package:

```
astrochem = pkgs.pythonPackages.toPythonModule (
  (pkgs.callPackage ./pkgs/astrochem { }).override { }
); 
```

**Comment by smaret** [comment]
> Does this work?
> 
> ```
> astrochem = pkgs.pythonPackages.toPythonModule (
>   (pkgs.callPackage ./pkgs/astrochem { inherit (pkgs) pythonPackages; }).override { }
> ); 
> ```

It does, in the sense that I can build `astrochem` from the `nur-packages-templates` fork:

```
% nix-build -I. -A astrochem
/nix/store/jhfcqypfc1z4ghcnwzpw3mdi3c6xymwp-astrochem
```

However, I don't know how to start a nix shell with the `astrochem` Python module to test it. With `nixpkgs`, I do the following:

```
% nix-shell -p python27Packages.astrochem --run python2
Python 2.7.15 (default, Jan  6 2019, 04:12:31)
[GCC 4.2.1 Compatible Clang 5.0.2 (tags/RELEASE_502/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import astrochem
>>>
```

I've tried something similar in the `nur-packages-templates` fork but it does not work:

```
% nix-shell -A astrochem --run python2
Python 2.7.15 (default, Jan  6 2019, 04:12:31) 
[GCC 4.2.1 Compatible Clang 5.0.2 (tags/RELEASE_502/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import astrochem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named astrochem
```

**Comment by Mic92** [comment]
`nix-shell -A astrochem --run python2` is not quite what you want.
You need a package that has astrochem in its `propagatedBuildInputs`
You can also write a `shell.nix` and put `astrochem` in.
It is now possible to refer to your local repository in NUR,
so you can check changes before pushing like this: https://github.com/nix-community/NUR#overriding-repositories

**Comment by smaret** [comment]
OK, thanks for your help.
