### ISSUE TITLE
error: attribute 'nur' in selection path 'nur.repos.mic92.inxi' not found .

### ISSUE THREAD

**Issue by LinArcX** [nix-community/NUR#126]
Hi. i follow the instructions in readme file. After adding nur in configuration.nix i can't install new package. ang get that error. why?

**Comment by Mic92** [comment]
Have you also added the lines to `~/.config/nixpkgs/config.nix` as described in the README? Otherwise `nix-env` as a user will not work. Adding the configuration only in `configuration.nix`, will only make the nur namespace available for the NixOS configuration.

**Comment by LinArcX** [comment]
@Mic92 Yes i add them.
