### ISSUE TITLE
What is the right way to port a nixpkgs contribution to NUR?

### ISSUE THREAD

**Issue by matthew-piziak** [nix-community/NUR#131]
I have a nixpkgs contribution [here](https://github.com/NixOS/nixpkgs/pull/54443) but I can't seem to attract any reviewer attention. Should I port it to NUR? What's the right way to go about doing that.

**Comment by Mic92** [comment]
I just responded to your pull request.

**Comment by rycee** [comment]
Perhaps this is closeable?
