### ISSUE TITLE
Pinning nixpkgs

### ISSUE THREAD

**Issue by danieldk** [nix-community/NUR#135]
Before submitting my repository to the NUR, I had a question with regards to pinning. My repository's `default.nix` takes `pkgs` as an argument, as usual. However, one derivation packages a Python module written in Rust (using `pyo3` and `pyo3-pack`). In this case I need to:

* Pin `nixpkgs` to a recent unstable. All the other derivations for Rust software in my repository uses `carnix`. However, here I need `buildRustPackage` since it works in combination with `pyo3-pack`. However, due to NixOS/nixpkgs#60668 , I need to pin `buildRustPackage` to get the same `cargoSha256` hashes on NixOS 19.03 and unstable.
* Currently `pyo3` uses features that are only available in nightly Rust versions. So, I need to use the package set from the Mozilla overlay to get a specific Rust nightly.

Is such selective pinning within specific derivations acceptable?

**Comment by bb010g** [comment]
For the first problem, I'd use a helper to mark things as broken, though you could also specify two hashes in a similar way: https://github.com/bb010g/nur-packages/blob/899971b797bb930a7dcdde567d23da98555d99eb/default.nix#L19-L23

For the second problem, it'd be really nice if there was a way to depend on packages from other NUR repos. I don't see how this could be built without pinning. The best interim solution here is probably to take a `mozilla-rust` package argument that could then be overriden with `{ mozilla-rust = pkgs.nur.repos.mozilla.rust; }`.

**Comment by danieldk** [comment]
> For the first problem, I'd use a helper to mark things as broken, though you could also specify two hashes in a similar way: https://github.com/bb010g/nur-packages/blob/899971b797bb930a7dcdde567d23da98555d99eb/default.nix#L19-L23

Thanks for your reply! I have solved this problem by moving everything to `buildRustCrate`. I am not using `pyo3-pack` anymore for building the Python modules.

> For the second problem, it'd be really nice if there was a way to depend on packages from other NUR repos. I don't see how this could be built without pinning. The best interim solution here is probably to take a `mozilla-rust` package argument that could then be overriden with `{ mozilla-rust = pkgs.nur.repos.mozilla.rust; }`.

That's a great idea! I'll add an argument so that people can override the Rust package.

**Comment by rycee** [comment]
Seems everybody is happy in here. So perhaps it is OK to close this issue? 🙂
