### ISSUE TITLE
Why isn't NUR managed as a channel?

### ISSUE THREAD

**Issue by ersinakinci** [nix-community/NUR#150]
I'm a new Nix user and I came across NUR while trying to set up [nixify](https://github.com/kampka/nixify).

My main question is, why isn't NUR structured as a Nix channel? That is, why do we need to set it up using all this (seemingly non-standard) import stuff? Seems to me (as a new user) like that's what the `nix-channel` tool was made for. Or more broadly, what's the rationale for NUR's distribution mechanism?

Thanks for all your work!

**Comment by zimbatm** [comment]
Hi @earksiinni. Good question.

It's possible to add any GitHub repository as a channel like this:
```
$ nix-channel --add https://github.com/nix-community/NUR/archive/master.tar.gz nur
$ nix-channel --update
these derivations will be built:
  /nix/store/iq7prfl1d443gn62kyr48x4pffmw4gi5-nur.drv
building '/nix/store/iq7prfl1d443gn62kyr48x4pffmw4gi5-nur.drv'...
unpacking channels...
created 1 symlinks in user environment
```

Now you should get a result for this command:
```
$ nix eval '(<nur>)'
/home/youruser/.nix-defexpr/channels/nur
```

Then change the nix code to use `<nu>` instead of the `builtins.fetchTarball ...`. Eg:

```nix
{
  packageOverrides = pkgs: {
    nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {
      inherit pkgs;
    };
  };
}
```
Becomes:
```nix
{
  packageOverrides = pkgs: {
    nur = import <nur> {
      inherit pkgs;
    };
  };
}
```

That would work too.

On the plus side, the nix code is simpler. It also allow you to control when the nur repo gets updated (the builtins.fetchTarball refreshes every TTL).
On the downside, it means that the system needs the <nur> channel to evaluate properly.

Hope this makes sense.

**Comment by earksiinni** [comment]
@zimbatm, thanks for the explanation. That makes sense.

What does "the system needs the channel to evaluate properly" mean exactly? Is there a reason why NUR's default.nix wouldn't evaluate properly? I guess I'm trying to understand why this installation method isn't mentioned in the README.md/why isn't it the default?

**Comment by zimbatm** [comment]
Let's say that you make a fresh install of your system. Without the channel, the nix code will fail with an error like:
```
error: file 'nur' was not found in the Nix search path (add it using $NIX_PATH or -I), at ...
```
You would have to remember to first add the NUR channel again.

**Comment by Mic92** [comment]
I personally preferred the declarative way, which is why included it in the README, but channels also can have there advantages.

In the near futures we should see if we can support flakes.

**Comment by rycee** [comment]
I've always used the channel method and have not had any issues with it
```console
$ sudo nix-channel --list | grep nur
nur https://github.com/nix-community/NUR/archive/master.tar.gz
```

**Comment by lolbinarycat** [comment]
further question: why does nur need to be an override? why can't it just exist as a separate channel?

**Comment by Mic92** [comment]
It can be. It's just a matter of test. The override allows to load packages from different places where you have pkgs.

**Comment by lolbinarycat** [comment]
@Mic92 that should be in the documentation somewhere.  currently users could easily think that making nur an override is required for it to function.

**Comment by Mic92** [comment]
@lolbinarycat pull requests are welcome.

**Comment by lolbinarycat** [comment]
@Mic92 
1. adding an override is actually required
2. see my pull request
