### ISSUE TITLE
No repos.json.lock updates

### ISSUE THREAD

**Issue by sikmir** [nix-community/NUR#182]
I've just noticed that last 5 requests from my [nur-packages](https://github.com/sikmir/nur-packages/) repo CI did not lead to automatic update of `repos.json.lock`:
```sh
$ if [ "false" = "${TRAVIS_PULL_REQUEST}" -a "master" = "${TRAVIS_BRANCH}" ]; then curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"; fi
{
  "@type": "pending",
  "remaining_requests": 50,
  "repository": {
    "@type": "repository",
    "@href": "/repo/5040084",
    "@representation": "minimal",
    "id": 5040084,
    "name": "NUR",
    "slug": "nix-community/NUR"
  },
  "request": {
    "repository": {
      "id": 123327588,
      "vcs_type": "GithubRepository",
      "owner_name": "nix-community",
      "name": "NUR"
    },
    "user": {
      "id": 42068
    },
    "id": 300997099,
    "message": "requested rebuild",
    "branch": "master",
    "config": {
    }
  },
  "resource_type": "request"
}
Done. Your build exited with 0.
```
What's going on?

**Comment by Mic92** [comment]
Use pkgs.fetchurl instead of builtins.fetchtarball: https://travis-ci.com/nix-community/NUR/builds/148133424#L634 to fix the evaluation.

**Comment by sikmir** [comment]
I see, that's caused by [niv](https://github.com/nmattia/niv) update (`sources.nix`).
To fix the problem:
`niv modify <pkg> -a builtin=false`
cc @nmattia

**Comment by nmattia** [comment]
https://github.com/nmattia/niv/issues/198

**Comment by sikmir** [comment]
@Mic92 It looks like NUR update endpoint doesn't work:
```sh
$ if [ "false" = "${TRAVIS_PULL_REQUEST}" -a "master" = "${TRAVIS_BRANCH}" ]; then curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"; fi
{
  "@type": "pending",
  "remaining_requests": 48,
  "repository": {
    "@type": "repository",
    "@href": "/repo/5040084",
    "@representation": "minimal",
    "id": 5040084,
    "name": "NUR",
    "slug": "nix-community/NUR"
  },
  "request": {
    "repository": {
      "id": 123327588,
      "vcs_type": "GithubRepository",
      "owner_name": "nix-community",
      "name": "NUR"
    },
    "user": {
      "id": 42068
    },
    "id": 327494485,
    "message": "requested rebuild",
    "branch": "master",
    "sha": null,
    "merge_mode": null,
    "config": null
  },
  "resource_type": "request"
}
```
But no NUR travis build triggered (https://travis-ci.com/github/nix-community/NUR/builds), no repos.json.lock update.

**Comment by Mic92** [comment]
@sikmir it does not update your repository because it use `builtins.fetchTarball` instead of `fetchurl`: https://travis-ci.com/github/nix-community/NUR/jobs/315066992#L329

**Comment by sikmir** [comment]
> @sikmir it does not update your repository because it use `builtins.fetchTarball` instead of `fetchurl`: https://travis-ci.com/github/nix-community/NUR/jobs/315066992#L329

My bad, I was sure that I use builtin=false everywhere. Fixed, it works now.
