### ISSUE TITLE
split up ci/deploy.sh in dedicated jobs

### ISSUE THREAD

**Issue by mrVanDalo** [nix-community/NUR#192]
it seems that `ci/deploy.sh` is doing multiple things.

* check for indention/linting and updates the master branch
* update `nix-combined`
* maybe more

it would be best to split this script up in multiple dedicated jobs.

**Comment by mrVanDalo** [comment]
cc @Mic92

**Comment by Mic92** [comment]
agreed.

**Comment by mrVanDalo** [comment]
Alright, I will take care of it at some point soon.

**Comment by Mic92** [comment]
Also fixed in https://github.com/nix-community/NUR/pull/191
