### ISSUE TITLE
Can't use a NUR package from nix-env

### ISSUE THREAD

**Issue by Xe** [nix-community/NUR#212]
```console
$ nix-env -iA nur.repos.xe.ii
error: NUR import call didn't receive a pkgs argument, but the evaluation of NUR's xe repository requires it.

This is either because
  - You're trying to use a package from that repository, but didn't pass a `pkgs` argument to the NUR import.
    In that case, refer to the installation instructions at https://github.com/nix-community/nur#installation on how to properly import NUR

  - You're trying to use a module/overlay from that repository, but it didn't properly declare their module.
    In that case, inform the maintainer of the repository: https://github.com/Xe/xepkgs
```

```console
$ sudo nix-channel --list
dhall https://hydra.dhall-lang.org/jobset/dhall-haskell/master/channel/latest
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixos https://nixos.org/channels/nixos-20.03
nur https://github.com/nix-community/NUR/archive/master.tar.gz
```

```console
$ cat ~/.config/nixpkgs/config.nix
{
  packageOverrides = pkgs: {
    nur = import <nur> {
      inherit pkgs;
    };
  };
}
```

What am I doing wrong? I get this error with nearly _every_ nur repo too.

**Comment by Mic92** [comment]
Does `nix-env -f '<nixpkgs>' -iA nur.repos.mic92.cntr` works?

**Comment by Mic92** [comment]
What happens here is that `nix-env` picks up the nix channel instead of using nixpkgs. Only nixpkgs will respect the `packageOverrides` in `config.nix`, which performs the right import. It might be worth documenting this.

**Comment by Xe** [comment]
Yes that works, I expected `nix-env` to work the same as `nix-shell` though. Should I file this as a bug with upstream?

**Comment by Mic92** [comment]
I think this has to be this way by design. nix-env allows to install packages from different channel versions, which are all independent nixpkgs repositories.
nix-shell on the other hand imports 'nixpkgs' explicitly when used with the `-p` parameter: https://github.com/NixOS/nix/blob/master/src/nix-build/nix-build.cc#L266

**Comment by Xe** [comment]
Fair enough! Thanks.
