### ISSUE TITLE
Module conflict

### ISSUE THREAD

**Issue by gnidorah** [nix-community/NUR#215]
What if I want a modified module derivation of a module that already exists in nixpkgs
How to do this?
For e.g. If I currently import tox from nur
```nix
  imports =
    [
      nur-no-pkgs.repos.tox.modules.tox-node
    ];
```
I will get an error 
```
error: The option `services.tox-node.enable' in `/home/gnidorah/tmp/nixpkgs/nixos/modules/services/networking/tox-node.nix' is already declared in `/nix/store/3vcj51zf0d613q5axpvbpy27vpmfvgkm-source/modules/services/tox-node.nix'.
(use '--show-trace' to show detailed location information)
```

**Comment by Mic92** [comment]
If you add conflicting options your best shot would be to namespaces it, i.e. `gnidorah.services.tox-node.enable`. I don't see any other way.

**Comment by gnidorah** [comment]
@Mic92 Got it, thank you!
