### ISSUE TITLE
CI cannot evaluate my repo: cannot import …, since path … is not valid

### ISSUE THREAD

**Issue by splintah** [nix-community/NUR#255]
Hi, [my repo](https://github.com/splintah/nurpkgs) fails to evaluate on CI with the following error:
```
INFO:nur.update:Evaluate repository splintah
error: while evaluating 'callPackageWith' at /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/lib/customisation.nix:117:35, called from /nix/store/5c7dpv4c7w7ywfa2fhgfb5hmzmm8bbh5-source/default.nix:18:13:
while evaluating 'makeOverridable' at /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/lib/customisation.nix:67:24, called from /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/lib/customisation.nix:121:8:
while evaluating anonymous function at /nix/store/5c7dpv4c7w7ywfa2fhgfb5hmzmm8bbh5-source/pkgs/passenv/default.nix:1:1, called from /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/lib/customisation.nix:69:16:
while evaluating 'callPackage' at /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:114:22, called from /nix/store/5c7dpv4c7w7ywfa2fhgfb5hmzmm8bbh5-source/pkgs/passenv/default.nix:2:1:
while evaluating 'callPackageWithScope' at /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:74:37, called from /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:114:28:
while evaluating 'makeOverridable' at /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/lib/customisation.nix:67:24, called from /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:97:8:
while evaluating 'drvScope' at /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:87:18, called from /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/lib/customisation.nix:69:16:
cannot import '/nix/store/xzxn1nljh9v6s67rz3c20pj09rlma00h-source/passenv.nix', since path '/nix/store/vpypdk51jawgjnqjkw5isg813zv2kagm-source.drv' is not valid, at /nix/store/3jkiz15ahalhag2br61cxqjpzackw8c6-nixpkgs-20.09pre236502.ccd458053b0/nixpkgs/pkgs/development/haskell-modules/make-package-set.nix:83:54
ERROR:nur.update:repository splintah failed to evaluate: splintah does not evaluate:
```

I cannot reproduce this on my own machine.

The failing expression is essentially (I inlined some imports):

```nix
{ pkgs ? import <nixpkgs> { } }:
let
  source = pkgs.fetchFromGitHub {
    owner = "splintah";
    repo = "passenv";
    rev = "00f6d61f741a6928984477b7da07c421be77ec85";
    sha256 = "18c67wq5w577h2zr8ga7fs8gpr017bwf5gdy7q65hwrbmayc9bvp";
  };
in
pkgs.haskellPackages.callPackage "${source}/passenv.nix" { }
```

I don't understand what is going wrong here. The same kind of error seems to be thrown for the repository named `jomik`, so maybe there is a similar cause between my repo and theirs.

**Comment by Mic92** [comment]
You are using import-from-derivation. We don't support this in NUR because we want full control over the nix expression for backup purposes and performance reason. If you want to import a third-party expression, there are two options: 1. Import as a submodule. 2. Copy only expression but keep the source seperated. In your case I would suggest the second option since this way you keep your repository smaller since NUR and its user don't need to download the source code.

**Comment by splintah** [comment]
Ah, makes sense, thanks.

I suspected something like this to be the cause, but I was wondering why something like the following (which does the same thing as far as I can see), can make it into `nur-combined`: https://github.com/nix-community/nur-combined/blob/2430b571ffc0682c69a59f03688b199f249c3c05/repos/balsoft/pkgs/default.nix#L6.

I guess this might be added before the blocking mechanism was in place.

**Comment by Mic92** [comment]
> Ah, makes sense, thanks.
> 
> I suspected something like this to be the cause, but I was wondering why something like the following (which does the same thing as far as I can see), can make it into `nur-combined`: [nix-community/nur-combined@`2430b57`/repos/balsoft/pkgs/default.nix#L6](https://github.com/nix-community/nur-combined/blob/2430b571ffc0682c69a59f03688b199f249c3c05/repos/balsoft/pkgs/default.nix#L6).
> 
> I guess this might be added before the blocking mechanism was in place.

I think we don't evaluate those packages there because it is nested in `pkgs = {}` without `recurseIntoAttrs`

**Comment by splintah** [comment]
> I think we don't evaluate those packages there because it is nested in `pkgs = {}` without `recurseIntoAttrs`

Hm, so I guess that could also be a solution to my problem, then. Is that actually desired behaviour?

**Comment by Mic92** [comment]
> > I think we don't evaluate those packages there because it is nested in `pkgs = {}` without `recurseIntoAttrs`
> 
> Hm, so I guess that could also be a solution to my problem, then. Is that actually desired behaviour?

It won't show up in our NUR search because we won't evaluate meta attributes for those packages.

**Comment by ncfavier** [comment]
I'm getting this (only in CI):

https://github.com/ncfavier/config/runs/4599227705?check_suite_focus=true#step:7:13

where the failing line is https://github.com/nix-community/NUR/blob/b9810aabbd64485f31bea99096af5fae26177689/lib/evalRepo.nix#L25

Is this the same issue?

**Comment by ncfavier** [comment]
Why did the original issue only occur on CI?

**Comment by ncfavier** [comment]
Also it only seems to be happening when running `nix flake check --no-build`.
