### ISSUE TITLE
tarballs in @shamilton repository 

### ISSUE THREAD

**Issue by Mic92** [nix-community/NUR#261]
Could you please not commit files like this? https://github.com/nix-community/nur-combined/blob/0e9b068c96fe51a48e78d0a070dc7ee7b4a63089/repos/shamilton/pkgs/FakeMicWavPlayer/src.tar.gz

@SCOTT-HAMILTON

We need to download repositories in our CI and large binary files will slow down the process for everyone. For now I stopped updating your repository.

**Comment by Mic92** [comment]
If you need to host files, you can create a fake release in your repository and attach files there.

**Comment by SCOTT-HAMILTON** [comment]
I apologize for the inconvenience, I've forced pushed and it should be fixed by now, could I be added back to the CI building list?

**Comment by Mic92** [comment]
done in https://github.com/nix-community/NUR/pull/262
