### ISSUE TITLE
Package search incomplete

### ISSUE THREAD

**Issue by tokudan** [nix-community/NUR#275]
The package search at https://nur.nix-community.org/ is missing repos, at least my repo is not included, while the nur-combined includes my repo.

**Comment by 0x4A6F** [comment]
Also my repo doesn't show up in search, but is accessible through http://nur.nix-community.org/repos/0x4a6f/.

**Comment by piegamesde** [comment]
Maybe related: Some packages are missing from the list. I have definitively packaged more than only one, but they don't show up.

https://nur.nix-community.org/repos/piegames/

![image](https://user-images.githubusercontent.com/14054505/97642184-d47d1e80-1a44-11eb-9a0a-2894b0c61490.png)

I suspect that this is because I don't declare those with `packageName = pkgs.callPackage ./path.nix {};` but by inheriting them as attributes from another struct.

**Comment by Mic92** [comment]
@piegamesde there is only one package here as far as I can tell: https://github.com/nix-community/nur-combined/blob/e7414bdf3d04a4dfc80002c211d67a1a54845faa/repos/piegames/default.nix#L30

**Comment by Mic92** [comment]
@tokudan are you packages back? https://github.com/nix-community/nur-combined/blob/e7414bdf3d04a4dfc80002c211d67a1a54845faa/repos/tokudan/default.nix#L18 http://nur.nix-community.org/repos/tokudan/

**Comment by Mic92** [comment]
@0x4A6F I need to look in your repo. it currently returns 404: https://github.com/nix-community/NUR/issues/275#issuecomment-714774801

**Comment by piegamesde** [comment]
@Mic92 Oops, my bad. `buildShellExtension` is not a package (would be cool if the search could show it nevertheless, maybe as `lib` items?) and the other ones (commented out) didn't build because they use import from derivation. Nevermind, then.

**Comment by tokudan** [comment]
My packages are now showing up. Is it clear what happened to have them show up or did they just show up at some random point?

**Comment by Mic92** [comment]
> My packages are now showing up. Is it clear what happened or did they just show up at some random point?

Yes. There was a bug in the static site generator that prevented updates.

**Comment by 0x4A6F** [comment]
The problem with my repo are gone after #310 and #311.

**Comment by Mic92** [comment]
Thanks. Closing this.
