### ISSUE TITLE
some emacs packages are broken when using nix-community/NUR

### ISSUE THREAD

**Issue by bbigras** [nix-community/NUR#291]
I got errors like: `Error (use-package): dap-mode/:config: Symbol’s function definition is void: dap-ui-mode`.

If I revert nix-community/NUR to c72aeb2ac8421632609f444b8a60897ad3753a7d it works again.

I'm using the emacs-init module with the emacs overlay and pkgs.emacsGit.

**Comment by Mic92** [comment]
I am not quite sure how your emacs interact with NUR? Are you using a package from a NUR repository? In that case you should get in touch with the NUR repository owner.

**Comment by bbigras** [comment]
reported to https://gitlab.com/rycee/nur-expressions/-/issues/23
