### ISSUE TITLE
Impurity when using latest master as a flake

### ISSUE THREAD

**Issue by antifuchs** [nix-community/NUR#294]
I'm trying to make a system config that uses nix flakes which pull in NUR recursively ([rnix-lsp](https://github.com/nix-community/rnix-lsp) if it's relevant). Unfortunately, the current version of NUR does not build as a flake, due to impure usage of `<nixpkgs>` in default.nix.

Here's a (minified) reproducer flake.nix, which I hope should build if NUR worked as a flake:

``` nix
{
  description = "A repro flake";

  inputs = {
    nur.url = "github:nix-community/NUR/master";
  };

  outputs = { self, nur }: {
    packages.x86_64-darwin.hello = (import nur {}).repos.mic92.hello-nur;
  };
}
```

Building this with `$(nix-build '<nixpkgs>' -A nixFlakes --no-out-link)/bin/nix flake --experimental-features "flakes nix-command" check` results in the following output:

```
error: --- ThrownError ----------------------------------------------------------------------------------------------------------------------------------------------------- nix
at: (1:20) in file: /nix/store/4vld4ff9yvsw4mf2zlh6s54vnvybn12n-source/default.nix

     1| { nurpkgs ? import <nixpkgs> {} # For nixpkgs dependencies used by NUR itself
      |                    ^
     2|   # Dependencies to call NUR repos with

cannot look up '<nixpkgs>' in pure evaluation mode (use '--impure' to override)
(use '--show-trace' to show detailed location information)
```

**Comment by Mic92** [comment]
You can do something like:

```
   packages.x86_64-darwin.hello = (import nur {
      nurpkgs = nixpkgs.legacyPackages.x86_64-darwin;
      pkgs = nixpkgs.legacyPackages.x86_64-darwin;
    }).repos.mic92.hello-nur;
```

**Comment by antifuchs** [comment]
Now that I better understand how things in flakes work together, I think NUR's flake definition is pretty much correct (and my usage was not). Thanks for explaining!
