### ISSUE TITLE
NUR doesn't update

### ISSUE THREAD

**Issue by dukzcry** [nix-community/NUR#298]
Hi @Mic92!
I see that 
https://github.com/nix-community/NUR and https://github.com/nix-community/nur-combined
have no update for 5 days
Something broke down?
Thanks.

**Comment by Mic92** [comment]
Thanks for letting us now. Apparently we do pay travis ci not enough: https://travis-ci.com/github/nix-community/NUR/jobs/447081918

**Comment by Mic92** [comment]
I look into switching to GitHub actions.

**Comment by Mic92** [comment]
updating fixed. I still need fix updating nur-search.

**Comment by Mic92** [comment]
Both are fixed.
