### ISSUE TITLE
Add more maintainer for this repo

### ISSUE THREAD

**Issue by Mic92** [nix-community/NUR#30]
Most pull requests to this repository will be trivial changes to repos.json.
Until we have figured out how to merge those automatically, it would be cool
to have more maintainers beside me that could merge those pull requests.

**Comment by Mic92** [comment]
cc @makefu @Lassulus @Infinisil @zimbatm or others I have not mentioned here.

**Comment by zimbatm** [comment]
Happy to be a maintainer and add the rest of the list if I get a :+1: from them

**Comment by makefu** [comment]
I am happy to join!

**Comment by Mic92** [comment]
I added you both to the list.

**Comment by zimbatm** [comment]
I just created the @nix-community/nur group and added us :D

**Comment by Infinisil** [comment]
I'd be happy to join and help with that :D

Question: The only conditions for a person's repository to get added to the list are:
- Key has something to do with them (github handle / organisation name / company name)
- The nur/update.py script runs successfully

That sound good?

**Comment by zimbatm** [comment]
Sounds good to me! I think the second point is already enforced by CI.

**Comment by Mic92** [comment]
Four maintainers should be enough for the beginning.
