### ISSUE TITLE
Installation Problem - Fresh install 20.09

### ISSUE THREAD

**Issue by dvogeldev** [nix-community/NUR#307]
Recently switched from arch to nixos. I am having problems with the installation of NUR.

On a fresh install NixOs 20.09
1. **First attempt**  nixpkgs.config.packageOverrides = pkgs: {
	```
	{ config, pkgs, ... }:

	{

	nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {
      		inherit pkgs;
	};

	imports = ...

	}
	```
This seems to install correctly, but when I do a simple test with mic92.hello-nur
	```
	`nix-shell -p nur.repos.mic92.hello-nur`
	```
This errors out with
	>  error: attribute 'nur' in selection path 'nur.repos.mic92.hello-nur' not found

2. **Second attempt** using nix-channels
	```
	nix-channel --add "https://github.com/nix-community/NUR/archive/master.tar.gz nur
	nix-channel --update
	
	nix eval '(<nur>)'
	# Returns "nur https://github.com/nix-community/NUR/archive/master.tar.gz"
	```
In the configuration.nix file
	```
	packageOverrides = pkgs: {
	  nur = import <nur> {
	    inherit pkgs;
	  };
	};
	```
This errors out with a similar response received when doing the hello-nur test
	> error: undefined variable 'nur' at (string):1:94 (use '--show-trace' to show detailed location information)

Running the same command with the --show-trace option

	> nix-shell -p nur.repos.mic92.hello-nur --show-trace
	>error: while evaluating the attribute 'buildInputs' of the derivation 'shell' at /nix/store/iy5z4hqz859d8adw2vdjfy40mv6cim2y-nixos-20.09.2387.0c81b9a4f17/nixos/pkgs/build-support/trivial-builders.nix:7:7:
	>while evaluating 'getOutput' at /nix/store/iy5z4hqz859d8adw2vdjfy40mv6cim2y-nixos-20.09.2387.0c81b9a4f17/nixos/lib/attrsets.nix:464:23, called from undefined position:
	>while evaluating anonymous function at /nix/store/iy5z4hqz859d8adw2vdjfy40mv6cim2y-nixos-20.09.2387.0c81b9a4f17/nixos/pkgs/stdenv/generic/make-derivation.nix:143:17, called from undefined position:
	>undefined variable 'nur' at (string):1:94

All this because I want to run Luke's DWM build. 
Any ideas in correcting the NUR install? What am I doing wrong? 
Thanks for the help.

**Comment by Mic92** [comment]
Your nix-shell will not use the override that you put in your NixOS `configuration.nix`. 

You need this in your `~/.config/nixpkgs/config.nix`:

```
{
  packageOverrides = pkgs: {
    nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/master.tar.gz") {
      inherit pkgs;
    };
  };
}
```
