### ISSUE TITLE
nur-search displays attribute incorrectly sometimes

### ISSUE THREAD

**Issue by crazazy** [nix-community/NUR#308]
Whenever a package is built using an `stdenv.mkDerivation` whose source is in nixos/nixpkgs, the attribute in https://nur.nix-community.org gets malformed

I think the issue lies mostly in this line, can anyone tell me why this line is neccessary in the first place? because the only thing it does is add the source location of the nixpkgs definition in parentheses.

https://github.com/nix-community/NUR/blob/6125b47fb8b971f22c8f334a6447a165a97d153e/nur/index.py#L45

**Comment by Mic92** [comment]
Maybe to strip `nur.`? I forgot. but using `print` might help.
