### ISSUE TITLE
add nixpkgs-mozilla to NUR?

### ISSUE THREAD

**Issue by zimbatm** [nix-community/NUR#32]
I think that it will have to be redefined as it's own fixed-point package set first

**Comment by Mic92** [comment]
Ideally the maintainer of project should request so that we know they actually care about this integration.

**Comment by tilpner** [comment]
@nbp @garbas Do you think this would be a good idea?

**Comment by garbas** [comment]
I (me personally) have no need for NUR integration, but others might have. Currently default.nix is a collection of all overlays that we provide. If somebody does the work and submits a PR I will be happy to review and potentially merge.

On the other hand it would be nice if NUR would play nice with projects that are based around overlays.

**Comment by zimbatm** [comment]
NUR supports overlays but they are opt-in by the user. Because NUR links to a bunch of user repos and we don't want to vet for every commit the trust model doesn't allow us to load all the overloads. But we can give references to the overlays that the users can then link to in a second stage.

**Comment by Mic92** [comment]
It is also possible to specify an alternative expression file to expose the overlay: https://github.com/nix-community/NUR#use-a-different-nix-file-as-root-expression

**Comment by nbp** [comment]
I have no need for it myself, but I am fine reviewing patches for adding it, as long as this does not distrub the overlay mechanism in place today.

**Comment by tilpner** [comment]
#77 is currently blocked on mozilla/nixpkgs-mozilla#110

Could be fixed by
- updating nixpkgs-mozilla servo (but hasn't been touched in 2 years)
- limiting package-set.nix to only provide things that evaluate
- deleting servo from nixpkgs-mozilla

**Comment by garbas** [comment]
@tilpner feel free to remove serve, ping me in PR and i'll review.

**Comment by Mic92** [comment]
@garbas here is the pull request: https://github.com/mozilla/nixpkgs-mozilla/pull/114
