### ISSUE TITLE
CI fails with absurd(?) error when evaluating package – cannot reproduce locally

### ISSUE THREAD

**Issue by jorsn** [nix-community/NUR#330]
In [this build](https://github.com/jorsn/nur-packages/runs/1989521729) the GitHub Action fails evaluating *patoline* because it is missing *imagelib-unix*. Locally I can evaluate it, and *imagelib-unix* exists for all ocaml versions.

Trying locally the exact command the ci uses I get

~~~
$ cat test                                                        
nix-env -f . -qa \* --meta --xml \
  --allowed-uris https://static.rust-lang.org \
  --option restrict-eval true \
  --option allow-import-from-derivation true \
  --drv-path --show-trace \
  -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
  -I $PWD
$ bash test
error: --- RestrictedPathError -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix-env
access to path '/home/johannes/.rcs/nix/nur-packages' is forbidden in restricted mode
~~~

Without restricted mode, everything evaluates fine.

How can I debug this? Does anybody know what could be wrong? It seems absurd to me.

**Comment by jorsn** [comment]
Ok, fixed. It was due to a package being deleted in Nixpkgs and different snapshots of Nixpkgs.

**Comment by Mic92** [comment]
Ok. Cool.
