### ISSUE TITLE
NUR's modules (, overlays and library) with Flake

### ISSUE THREAD

**Issue by augu5te** [nix-community/NUR#342]
I cite the README: "_Using overlays and modules from NUR in your configuration is fairly straight forward._" 

Well,  I struggled to access modules defined within NUR without trigger infinite recursion or be required to use `--impure`, below the result of my best attempt.  

I wonder if anyone has a better solution, a more straight forward way ? 

Flake support is experimental  but some status indication or examples about the usage of NUR's modules, overlays and library with Flake will be helpful in the README.

```nix
{
  description = "Test NUR's module";
  inputs.nur.url = "github:nix-community/NUR";
  outputs = { self, nixpkgs, nur }: rec {
    nixosConfigurations.myConfig = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        { nixpkgs.overlays = [ nur.overlay ]; }
        ({ pkgs, ... }:
          let
            nur-no-pkgs = import nur {
              nurpkgs = import nixpkgs { system = "x86_64-linux"; };
            };
          in {
            imports = [ nur-no-pkgs.repos.kapack.modules.oar ];
            services.oar.database = { host = "foo"; passwordFile = "/etc/foo"; };
            services.oar.client.enable = true;
          })
      ];
    };
    defaultPackage.x86_64-linux =
      nixosConfigurations.myConfig.config.system.build.vm;
  };
}
```

**Comment by Mic92** [comment]
Right now I only use the overlay, which seem to work with flake as well. If you have any solutions for loading other parts from NUR, feel free to document them in the README.

**Comment by iopq** [comment]
> Right now I only use the overlay, which seem to work with flake as well. If you have any solutions for loading other parts from NUR, feel free to document them in the README.

I have documented this way in the README: https://github.com/nix-community/NUR/pull/588
