### ISSUE TITLE
Move IRC channel to somewhere else

### ISSUE THREAD

**Issue by Mic92** [nix-community/NUR#360]
We currently have #nixos-nur on freenode.
Community is moving to Matrix. Where should we go?

**Comment by makefu** [comment]
We could simply follow nixos.org to the new matrix server?
Another option would be to follow #nixos-wiki or move to https://fairydust.space . matrix is federated so everything should be fine.
another option of course is to move to hackint or libera.chat

**Comment by Izorkin** [comment]
I am for the variant of moving to irc.libera.chat.

**Comment by Mic92** [comment]
I guess we could have both? Is nixos on matrix already bridged to libera?

**Comment by Izorkin** [comment]
There seems to be no bridge between matrix and libera

**Comment by Mic92** [comment]
I guess I could move the IRC channel and wait for https://github.com/matrix-org/matrix-appservice-irc/issues/1324 ?

**Comment by bignaux** [comment]
I vote to be independent of nixos.org matrix server.

**Comment by makefu** [comment]
my vote is for either libera or hackint but not necessarily matrix.

**Comment by bignaux** [comment]
i really don't get why people blame freenode new staff when all that is a bit complicated, https://gist.github.com/prawnsalad/4ca20da6c2295ddb06c1646791c61953 "Both sides had valid points, both sides extremely bad at communicating, both sides unable to work together." . I'd have let some chance to the new staff before be in a hurry.

**Comment by Mic92** [comment]
I follow development in #libera-matrix a bit and it looks like they are working on better matrix integration on their side (Even better than what freenode used to have, with their own home-server). They plan to have a bridge for testing ready in the 1-2 days. I want to wait so we can set up the new channel that in a way that is best for both IRC and matrix users.

**Comment by makefu** [comment]
If nothing but the staff would have been changed i think it would not be much of an issue. However it seems that the IRC policy has been changed to the worse. Discussion at https://lwn.net/Articles/857252/

**Comment by zimbatm** [comment]
Since it hasn't been mentioned before: OFTC has a Matrix bridge already and is independent of the FreeNode/Libera drama

**Comment by Mic92** [comment]
There is also now #nur:bethselamin.de on matrix. I guess this can be mirrored to the usual suspects.

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/NUR/commit/14e2122b8b1a82c149b93a97fcbb7a68bdd052ba
