### ISSUE TITLE
Evaluation timed out of after 5 seconds

### ISSUE THREAD

**Issue by sikmir** [nix-community/NUR#375]
From [update_nur](https://pipelines.actions.githubusercontent.com/uCzaclw094G0p6fwgCr6si7UNuzDeuY3XG8mNsRAA92UNVQCYv/_apis/pipelines/1/runs/11694/signedlogcontent/3?urlExpires=2021-08-19T21%3A04%3A25.1836639Z&urlSigningMethod=HMACV1&urlSignature=r%2BnWP3jQWotBj5%2FGJNYvlYqtJqM0oxL4aKR9ullAado%3D):
```
2021-08-19T20:57:46.6904760Z INFO:nur.update:Evaluate repository sikmir
2021-08-19T20:57:51.6925192Z ERROR:nur.update:repository sikmir failed to evaluate: evaluation for sikmir timed out of after 5 seconds
```
Is it some limitation for evaluation time? Repo evaluated on my [CI](https://github.com/sikmir/nur-packages/runs/3376018929?check_suite_focus=true) with no problems.

**Comment by Mic92** [comment]
The timeout is just a safety mechanism. I increased it to 10s.

**Comment by Mic92** [comment]
see https://github.com/nix-community/NUR/pull/524
