### ISSUE TITLE
my repo is not listed on nur-search

### ISSUE THREAD

**Issue by dukzcry** [nix-community/NUR#398]
Hi.
Can't get why my repo https://github.com/repos-holder/nur-packages is not listed on https://nur.nix-community.org/
And If I use direct link https://nur.nix-community.org/repos/dukzcry/ the list is very old

**Comment by Mic92** [comment]
Yes. The CI there is broken. Help wanted.

**Comment by VergeDX** [comment]
Same issues here, I noticed the one before me also not visible in nur-combined & nur-search.

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/NUR/pull/407
