### ISSUE TITLE
What's the correct way to detect nixpkgs release version?

### ISSUE THREAD

**Issue by YellowOnion** [nix-community/NUR#403]
Unstable has changed a lot of things that my package requires to build, and so I need to do various different things based on what release I'm building for.

**Comment by Mic92** [comment]
You can use `lib.version` to detect what nixpkgs version you are on: https://github.com/NixOS/nixos-hardware/blob/4045d5f43aff4440661d8912fc6e373188d15b5b/common/pc/laptop/default.nix#L9
