### ISSUE TITLE
access to canonical path ... is forbidden

### ISSUE THREAD

**Issue by tjni** [nix-community/NUR#438]
I'm experimenting with adding some packages to a custom NUR repository and got stuck when testing if my repository evaluates. It seems that access to the temporary directory that (I'm guessing) my repository is cloned into is forbidden?

```
❯ bin/nur update
INFO:nur.update:Evaluate repository tjni
error: access to canonical path '/private/tmp/tmpodewzjl7/default.nix' is forbidden in restricted mode
ERROR:nur.update:repository tjni failed to evaluate: tjni does not evaluate:
$ nix-env -f /tmp/tmpodewzjl7/default.nix -qa * --meta --xml --allowed-uris https://static.rust-lang.org --option restrict-eval true --option allow-import-from-derivation true --drv-path --show-trace -I nixpkgs=/nix/store/llj06jz3avacwki99lfvna7z1v3cbk4f-nixpkgs/nixpkgs -I /nix/store/587azbrljnxjg7xlsrjq88n0yqisry92-source -I /tmp/tmpodewzjl7/default.nix -I /Users/tni/code/NUR/lib/evalRepo.nix. This repo is not yet in our lock file!!!!
```

For what it's worth, I am on OSX, and I wonder if this is due to /tmp being a symlink to /private/tmp on OSX. However, I don't know enough about Nix to know how to verify that or otherwise debug this effectively. Any help would be welcome!

**Comment by Mic92** [comment]
Do you have the source code publish somewhere. You are doing import from derivation somewhere but I cannot give hints until I see the code on how to fix it.

**Comment by Mic92** [comment]
Sorry. I never followed up on that. Is this still an issue? The only package I see seems fine

**Comment by Mic92** [comment]
I consider this solved.
