### ISSUE TITLE
Repository syntax change

### ISSUE THREAD

**Issue by Infinisil** [nix-community/NUR#45]
With the merging of https://github.com/nix-community/NUR/pull/27, a new syntax for repositories is desired. While the old syntax will still work just fine as of now, it has problems with NixOS modules, so it would be good to get away from it. Users will get a warning about that when they use repos with the old syntax:
```
    NUR repository ${prettyName} is using the deprecated callPackage syntax which
    might result in infinite recursion when used with NixOS modules.
```

Note that the installation instructions changed as well. The old way works just fine if you don't intend to use it on NixOS, but for the future the new way should be preferred. 

The following repositories should be updated:
- [x] dtz - @dtzWill - https://github.com/dtzWill/nur-packages/blob/master/default.nix
- [x] dywedir - @dywedir - https://github.com/dywedir/nur-packages/blob/master/default.nix
- [x] eeva - @jpotier - https://framagit.org/eeva/nur-packages/blob/master/default.nix
- [x] fgaz - @fgaz - https://github.com/fgaz/nur-packages/blob/master/default.nix
- [x] kampka - @kampka - https://github.com/kampka/nix-packages/blob/master/default.nix
- [x] ma27 - @Ma27 - https://gitlab.com/Ma27/nur-packages/blob/master/default.nix
- [x] manveru - @manveru - https://github.com/manveru/nur-packages/blob/master/default.nix
- [x] mpickering - @mpickering - https://github.com/mpickering/nur-packages/blob/master/default.nix
- [x] tilpner - @tilpner - https://github.com/tilpner/nur-packages/blob/master/default.nix

### Migration and new features
Now your main `default.nix` file should only take one argument, namely `pkgs`. So if you had something like this before:
```nix
{ callPackage, stdenv }: {
  foo = callPackage ./foo;
  bar = stdenv.mkDerivation { /* ... */ };
}
```
The new syntax looks like this:
```nix
{ pkgs }: {
  foo = pkgs.callPackage ./foo;
  bar = pkgs.stdenv.mkDerivation { /* ... */ };
}
```

This now allows you to provide usable NixOS modules and overlays (by convention in the `modules`/`overlays` attributes):
```nix
{ pkgs }: {
  foo = pkgs.callPackage ./foo;
  modules.xserver = { pkgs, config, lib, ... }: {
    services.xserver.enable = true;
  };
  overlays.hello = self: super: {
    hello = super.hello.override { ... };
  };
}
```

You need to make sure to not evaluate the `pkgs` argument for modules. This will give an error when somebody tries to use the module from NUR:

```nix
{ pkgs }: with pkgs; {
  foo = callPackages ./foo;
  modules.bar = { ... };
}
```

**Comment by Ma27** [comment]
thanks a lot for the notification! will have a look at it ASAP %)

**Comment by kampka** [comment]
@Infinisil Done :+1:

**Comment by dtzWill** [comment]
Done!

**Comment by Ma27** [comment]
fixed as well, thanks a lot for your effort!

**Comment by dywedir** [comment]
@Infinisil thanks! 
done

**Comment by manveru** [comment]
Done :)

**Comment by jpotier** [comment]
updated

**Comment by mpickering** [comment]
Updated now in a9fca19

**Comment by Infinisil** [comment]
Thanks everybody!

**Comment by Ma27** [comment]
...and thanks for your work to make this possible!

**Comment by Mic92** [comment]
@Infinisil Now this could become a failure instead of a warning.
