### ISSUE TITLE
if NUR has lock file, maybe combined repository should be provided/generated?

### ISSUE THREAD

**Issue by dtzWill** [nix-community/NUR#46]
Basically once a particular NUR revision is fetched, exploring each of the contained repositories requires an additional fetch-- which is another delay and unless pre-fetched breaks the use of `nix search`/`nix-env -qa` and prevents tab-completion in a shell ).

Not a huge problem maybe but after running into this a few times I can't help but feel that pointing my config at a combination of evertyone's repository (esp if done by a travis job such that XZ can be used instead of gzip...) would provide a much better experience and generally still be small enough to be very fast.

To mitigate this issue I've also added my own repo directly in my config (no eval checks but hopefully I will be forgiving of myself if I break things :P).

Maybe this is not a direction NUR wants to pursue, but maybe it is! Let's discuss and sort out what sounds good to everyone.

Thanks!

**Comment by Mic92** [comment]
For some internal task it would be beneficial if we had pre-fetched sources for both the repositories and the resulting tarball (in case repositories become unavailable).

**Comment by Mic92** [comment]
What is already possible but not documented is to use a channel to maintain NUR: https://github.com/NixOS/nixos-hardware#setup

I think it make sense to also provide a fat tarball as an alternative to our `fetchTarball` approach.

**Comment by tilpner** [comment]
> Do we need a repository size policy?

Only for the combined delivery method. It should be easy to keep certain larger repositories linked dynamically from that combined expression.

The usage examples section mentions "Automatic generated package sets (i.e. generate packages sets from PyPi or CPAN)", so forbidding large repos in general would be misleading.

**Comment by Mic92** [comment]
Repositories bigger then X could be excluded automatically from being bundled in the lock file and we fallback to importing them via fetches in that case.

**Comment by Mic92** [comment]
Now that we have a channel, what is the best way to use it as such?

**Comment by Mic92** [comment]
cc @Infinisil
