### ISSUE TITLE
hash mismatch on repo ( wolfangaukang )

### ISSUE THREAD

**Issue by fabianhjr** [nix-community/NUR#466]
Error on home-manager using package `nur.repos.wolfangaukang.vdhcoapp`

```
error: hash mismatch in fixed-output derivation '/nix/store/q2s08xjxw7mk43abbmz50gf7lphf4ixp-nix-agordoj-51a8f46.drv':
         specified: sha256-O2EqyeMbRJVK5RL/vArWlYhDn5ZhwvkMRHe05FwfSlw=
            got:    sha256-Ffep6TAGRJwyZh8snAdB7G/Z9T4fxKu/xqdXXe2d//Q=
```

From: https://github.com/nix-community/NUR/blob/ccc61f9707bfc0d8f6108b334bca9a0d16ea4b02/repos.json.lock#L994-L998

Last commit: https://github.com/nix-community/NUR/commit/7fe56a7ba4c5b778fba325d82523f75208d20dc2

Unsure about cause since just two days ago a home-manager generation was built on my system without errors.

**Comment by WolfangAukang** [comment]
Excuse me, what is expected from my side here? Although I understand why I was pinged, I'm not sure what is expected from me to do.

**Comment by fabianhjr** [comment]
I don't understand the cause either so closed as something that didn't need fixing now that the pinned version/revision/hash moved forward.
