### ISSUE TITLE
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by zimbatm** [nix-community/NUR#48]
This output appears in the logs. I have seen it in other repos that use the Travis + Nix setup as well.

**Comment by samueldr** [comment]
I think this is something that can be fixed using `glibcLocales` and setting `LOCALE_ARCHIVE` like so:

```
LOCALE_ARCHIVE="${pkgs.glibcLocales}/lib/locale/locale-archive";
```

That's something that is sometimes needed with nix on non-NixOS linux platforms.

**Comment by Mic92** [comment]
Probably wrapping the ci stuff in a release.nix could help.

**Comment by zimbatm** [comment]
It also happens on Darwin where `glibcLocales` is not available
