### ISSUE TITLE
Nix VSCode Marketplace Integration

### ISSUE THREAD

**Issue by AmeerTaweel** [nix-community/NUR#480]
Recently, I created `nix-vscode-marketplace`, a flake that includes the 10k most popular extensions from the VSCode Marketplace, and all the extensions of OpenVSX. @LEv145 suggested we integrate this into the NUR in [this issue](https://github.com/AmeerTaweel/nix-vscode-marketplace/issues/2).

Do you think it's a good idea?

**Comment by Mic92** [comment]
Why not. What is the evaluation time for this repo?

**Comment by AmeerTaweel** [comment]
Sorry for the late reply. I was inactive for the last period because of my university.

Can you please tell me how do we check evaluation time? I see there is a `nix eval` command. Should I use this?

**Comment by Mic92** [comment]
We currently have a timeout for running nix eval:
https://github.com/nix-community/NUR/blob/3a5f3717d0b71ecdda7658e3bd54bc9ebeb408d5/ci/nur/update.py#L55

```
$ time nix-env -qa '*' --xml --meta --drv-path -f ./default.nix
```

It's limited to 10s but this limit was chosen arbitrarily to prevent NUR from breaking when indexing random repositories.

**Comment by AmeerTaweel** [comment]
Thanks.

I want to restructure this flake because the guys at `nixos-search` asked me to make the exported package set flat. Then I will evaluate it and report the results here.

**Comment by AmeerTaweel** [comment]
It seems that nix-vscode-marketplace will be merged into nixpkgs. So I'm closing this...
