### ISSUE TITLE
NUR cli idea

### ISSUE THREAD

**Issue by zimbatm** [nix-community/NUR#49]
It would be cool to provide a CLI that helps tending NUR and it's children. Something that would take the roles of `guix import` and `nix-prefetch-url` + updating

**Comment by Mic92** [comment]
I started this here: https://github.com/nix-community/NUR/commit/5311bb9fa2c9d7a67083435a3d326032347ab64b

**Comment by Mic92** [comment]
The only questions is what commands should be exposed and what are the internal ones, because I also see use cases for a companion application for end-users.

**Comment by zimbatm** [comment]
Yeah I think all commands will start for the main repo and some of them will turn out to be useful outside and be extracted at that point

**Comment by Mic92** [comment]
This was implemented in https://github.com/nix-community/NUR/pull/57
