### ISSUE TITLE
Provide pkgs argument when testing evaluation

### ISSUE THREAD

**Issue by ilya-fedin** [nix-community/NUR#496]
Currently the updating action seem to not to provide the argument when evaluating repositories, my repository fallbacks to a pinned nixpkgs commit (checked as successfully building) that doesn't seem to work in the restricted-eval mode. That wouldn't be a problem if the action used something like `--arg pkgs 'import <nixpkgs> {}`. I also guess that the first example provided in https://github.com/nix-community/NUR#how-to-add-your-own-repository doesn't evaluate on the action in reality as it requires the argument to be specified.

I don't really want to remove falling back to the pinned nixpkgs commit and my repository seem to be not updating since April...

**Comment by Mic92** [comment]
You can also provide an alternative entrypoint file for nur: https://github.com/nix-community/NUR/blob/master/repos.json#L37
if this helps.

**Comment by ilya-fedin** [comment]
Wow, thanks! What do you think about providing the argument though?

**Comment by ilya-fedin** [comment]
@Mic92 sorry for pinging you, I just want to hear your thoughts on this to get whether it's worth to wait for the argument to be provided or create a separate file for NUR... I mainly made the fallback to flake-compat due to a friend who uses my repository via NUR and it's convenient for him to just not specify pkgs for NUR and have the tested nixpkgs commit and get built packages from cachix. WIth a different file that would mean I have to guide him on overriding it back...

**Comment by Mic92** [comment]
Does it not provide the argument here?

https://github.com/nix-community/NUR/blob/2ff0d1346d6c6dadbb6435ac1d5e55c8ec9dec43/ci/nur/update.py#L27

**Comment by ilya-fedin** [comment]
Oh, I see what's the problem now, it's the `builtins.intersectAttrs`, it doesn't even pass `pkgs` as I have `{ ... } @ args` in the default.nix

**Comment by ilya-fedin** [comment]
Why it doesn't call like `expr passedArgs`? :thinking:

**Comment by ilya-fedin** [comment]
Ah, it's probably for those who use `{}:` or don't have a function at all... Anyway, I think I'll be able to fix this now on my end, thanks
