### ISSUE TITLE
`https://nur-update.herokuapp.com/update` returns application error

### ISSUE THREAD

**Issue by suhr** [nix-community/NUR#509]
Here: https://github.com/suhr/nur-packages/actions/runs/3595355242/jobs/6054740805#step:8:14

As a result, CI did not trigger the NUR update.

**Comment by graham33** [comment]
Seeing the same thing for my NUR repo (https://github.com/graham33/nur-packages/actions/runs/3596297697/jobs/6056804246)

**Comment by blakat360** [comment]
same with mine

**Comment by Mic92** [comment]
Heroku has canceled the free tier on this application.

**Comment by graham33** [comment]
> Heroku has canceled their free tier: https://www.heroku.com/pricing

That's frustrating. How complex is the app, would you be able to run it in their Eco/Basic tier? Happy to contribute something via BuyMeACoffee or similar...

**Comment by Mic92** [comment]
The code is super simple: https://github.com/nix-community/nur-update/blob/master/nur_update/__init__.py
I could also move this to our nix-community servers which would still people to migrate to a new domain: https://github.com/nix-community/nur-update/blob/master/nur_update/__init__.py

**Comment by Mic92** [comment]
Issue tracked here: https://github.com/nix-community/infra/pull/336

**Comment by Mic92** [comment]
This is how you can fix your repositories: https://github.com/nix-community/nur-packages-template/commit/71d59a8298859a90d09d658800f256931b85f3c0
