### ISSUE TITLE
Document how to test/use own repository

### ISSUE THREAD

**Issue by Mic92** [nix-community/NUR#53]
It should be straight forward to test expressions before pushing new content to a repository.
Therefore we should provide snippets on how load packages/modules/library/overlays functions from a local checkout into NixOS/Nix. If necessary helpers can be added to NUR that simplify the workflow.

**Comment by ZerataX** [comment]
I currently am trying to test a module I wrote and am stuck :/

**Comment by Mic92** [comment]
you can also override your own repository https://github.com/nix-community/NUR#overriding-repositories to update it more frequently than NUR.

**Comment by milahu** [comment]
> you can also override your own repository

so with `repoOverrides`, this issue is fixed...?

**Comment by Mic92** [comment]
I think so.
