### ISSUE TITLE
Feature Request: support `fetchtorrent`

### ISSUE THREAD

**Issue by mrtnvgr** [nix-community/NUR#627]
As the title says.

**Comment by Mic92** [comment]
Support in which way? It should work for derivations already and I don't see how it makes sense for fetching nur repositories, because there is no way to update these repo types.

**Comment by mrtnvgr** [comment]
> Support in which way? It should work for derivations already and I don't see how it makes sense for fetching nur repositories, because there is no way to update these repo types.

It doesn't work for me:
```console
$ nix-build -A package
error:
       … while calling the 'abort' builtin

         at /nix/store/byr4pm5fn5xpmqbr7g9njw16i3mhr1zg-nixos-23.05/nixos/lib/customisation.nix:179:65:

          178|
          179|     in if missingArgs == [] then makeOverridable f allArgs else abort error;
             |                                                                 ^
          180|

       error: evaluation aborted with the following error message: 'Function called without required argument "fetchtorrent" at /home/user/nurpkgs/....nix:1'
```

**Comment by Mic92** [comment]
Is your nixpkgs up-to-date? https://github.com/NixOS/nixpkgs/pull/263862

**Comment by mrtnvgr** [comment]
> Is your nixpkgs up-to-date? [NixOS/nixpkgs#263862](https://github.com/NixOS/nixpkgs/pull/263862)

Sorry for noise, my nixpkgs were pinned to latest release, not unstable. NixOS/nixpkgs#265560
