### ISSUE TITLE
Wanted: example of working nur-packages overlay

### ISSUE THREAD

**Issue by yurrriq** [nix-community/NUR#74]
Can someone point me to an example of a working overlay? I can't seem to figure out why this one doesn't work.. https://github.com/yurrriq/nur-packages/blob/31707d64/overlays/engraving.nix

**Comment by Mic92** [comment]
@mpickering added one https://github.com/mpickering/nur-packages/blob/master/default.nix
but I never tested it.

@Infinisil probably tested overlays, when he extended support beyond packages.

**Comment by mpickering** [comment]
For example: https://github.com/mpickering/haskell-nix-plugin/blob/master/default.nix

**Comment by yurrriq** [comment]
Thanks, I’ll check it out.

**Comment by yurrriq** [comment]
@Infinisil. Yeah, I know... my bad. Currently, I'm getting a segfault.. I'll try to come up with a minimum failing example, as there are lots of moving pieces.

**Comment by Infinisil** [comment]
A segfault certainly isn't caused by a misconfigured overlay. If anything, this means that it worked and some program has some problem with the changes.

**Comment by yurrriq** [comment]
Here's where the segfault happens:

```
...
evaluating file '/nix/store/b0y6wpa576j4gb1di368w9sy4abfcx0w-source/default.nix'
```
with this [default.nix](https://github.com/nix-community/NUR/blob/0be35ea1436aad01d0ea00b57e5154bd724bf9b5/default.nix)

**Comment by yurrriq** [comment]
fwiw I get a segfault when trying to use only mpickering's overlay above and no other `imports`, `overlays`, or `environment.systemPackages`... I'll come up with a minimum failing example and post it tonight.

**Comment by Infinisil** [comment]
If you actually found a segfault in the nix evaluator then I'll be impressed!

**Comment by Mic92** [comment]
Well it is still written in c++. Also I have seen more coredumps after an exception.

**Comment by yurrriq** [comment]
It turns out the issue was with [the expression](https://github.com/yurrriq/dotfiles/blob/d393b5f/nix/nixps/overlays-compat/overlays.nix) I was trying to use to achieve parity between system- and user-level overlays. I still want to get that working, but it's lower priority than getting nur-packages working in general, which I have now achieved. Thanks!
