### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by Mic92** [nix-community/NUR#755]
I am not using NUR directly myself actually for a while, but it seems that many other people do.
For me personally flakes have replaced the schema that I also introduced with NUR.
Therefore, I would like to transfer the project to a new maintainer.
The work is not too much for the most part as most repositories are self-contained.
However there are probably infrastructure and CI that could be improved.

I set the 01.01.2025 as a deadline, if there is no new maintainer found until than, I may archive the project by then.

**Comment by vedantmgoyal9** [comment]
Hi, I'm learning about Nix and am interested in becoming a maintainer.

**Comment by vedantmgoyal9** [comment]
@Mic92 Hi, I'm learning about Nix and am interested in becoming a maintainer.

**Comment by Mic92** [comment]
@vedantmgoyal9 I looked up and you don't seem to have a nur repository or any other nix-related contributions. What is your motivation for maintaining this repository?

**Comment by vedantmgoyal9** [comment]
As I said, I'm learning about Nix, and also, a few hours ago, I made my first contribution to nixpkgs. I'm developing a project [RustReleaser](https://github.com/rustreleaser-org/rustreleaser), which is "[goreleaser](https://github.com/goreleaser/goreleaser), but for rust", and that's where my Nix journey began :)

**Comment by vedantmgoyal9** [comment]
@Mic92 As I said, I'm learning about Nix, and, a few hours ago, I made my first contribution to nixpkgs too. I'm developing a project [RustReleaser](https://github.com/rustreleaser-org/rustreleaser), which is "[goreleaser](https://github.com/goreleaser/goreleaser), but for rust", and was looking to add functionality to publish packages to a nur. That's where my Nix journey began :)

**Comment by joaquinito2070** [comment]
I need to be a maintainer of NUR.

**Comment by Pandapip1** [comment]
I've got a lot of experience with nixpkgs, although I have no experience with NUR. I'd be happy to be a maintainer if it can avoid NUR shutting down.

**Comment by Mic92** [comment]
@Pandapip1 send you an invite

**Comment by Pandapip1** [comment]
> @Pandapip1 send you an invite

Already accepted it!

**Comment by Mic92** [comment]
Updated the repository.
