### ISSUE TITLE
Allow specifying branch in repos.json

### ISSUE THREAD

**Issue by lheckemann** [nix-community/NUR#78]
Currently nur is hardcoded, as far as I can tell, to use the master branch of whatever repo is being pointed to. It would be nice to allow choosing another branch.

**Comment by makefu** [comment]
@lheckemann do you have a specific case in mind where this feature would help? I am not sure if we we would create a feature for a non-existing use-case

**Comment by makefu** [comment]
ah cool, if there is a use case, then why not? :+1:

**Comment by Mic92** [comment]
Pull requests are welcome.

**Comment by Mic92** [comment]
Otherwise you can fork off the repository and change back to master.
