### ISSUE TITLE
Improve design of NUR search

### ISSUE THREAD

**Issue by Mic92** [nix-community/NUR#83]
I created something rather ugly for our search: https://nix-community.github.io/nur-search/
The page is build in this repository: https://github.com/nix-community/nur-search
This way everybody should feel enabled to do better. #hacktoberfest
Automated updates of this site will follow shortly.

**Comment by Mic92** [comment]
It is build with [hugo](https://gohugo.io/)

**Comment by bbigras** [comment]
Is it possible to just list all the available packages from every repos?

**Comment by Mic92** [comment]
Sure.

**Comment by mrVanDalo** [comment]
Is this related to #191 ?

**Comment by mrVanDalo** [comment]
closing this, because it seems there is nothing to do here.
